### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by abb1991** [ammueller/prj-rev-bwfs-dasmoto#2]
Your CSS looks good. I'd suggest styling elements directly so your don't have to access them through parent/child relationships. It'll make your code less likely to break if you add new HTML, or move different elements around.

Change
```
.brushes h2 {
  background-color: mediumspringgreen;
}

.frames h2 {
  background-color: lightcoral;
}

.paint h2 {
  background-color: skyblue;
}
```

to a class directly on the element:

```
.brushes {
  background-color: mediumspringgreen;
}

.frames {
  background-color: lightcoral;
}

.paint {
  background-color: skyblue;
}
```

**Comment by ammueller** [comment]
Thanks @abb1991! Changing this caused the entire div area to have a colored background rather than just the headings - but I will continue to play around to use less parent/child relationships
