### ISSUE TITLE
Global selector

### ISSUE THREAD

**Issue by abb1991** [ammueller/prj-rev-bwfs-dasmoto#3]
I noticed you used HTML as a selector:

```
html{
  font-family: Helvetica;
}

```
Here's the global  selector `*`

As a trick to better understand the CSS box model, try adding a 1px red border in your global selector:

```
*{
  border: 1px solid red;
}
```

Are there any differences between `*` and `html`?

**Comment by ammueller** [comment]
that's interesting! so `* `selects each individual element where `html` selects the body as a whole?
